print("---------------------------")
print("Mae Pranee kay Hoom.inc")
print("---------------------------")
print("Rocket         x 1 : 150m")
print("Satellite      x 1 : 65m")
print("Ticket to Moon x 1 : 1m")
print("Hotel on Mar   x 2 : 20m")
print("---------------------------")
print("             Total : 236m")