print("Welcome to FirstShop")
print("*********************")
print("Apple x ",3,30,"THB : ",3*30,"THB")
print("Banana x",1,10,"THB : ",1*10,"THB")
print("*********************")
print("Total",90+10,"THB")
print("Thank You : FirstShop")
print("---------------------")